---
- name: Shell | Install packages
  ansible.builtin.apt:
    name: "{{ shell_apt_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Shell | Set user shell
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: "{{ shell_user_shell }}"

- name: Shell | Set root shell
  ansible.builtin.user:
    name: root
    shell: "{{ shell_root_shell }}"
