---
- name: Shell | Install packages
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: Shell
    install_chocolatey_packages: "{{ shell_chocolatey_packages }}"
    install_scoop_packages: []
    install_winget_packages: []

- name: Shell | Resolve PowerShell profile path
  ansible.windows.win_powershell:
    script: |
      $documents = [Environment]::GetFolderPath('MyDocuments')
      $Ansible.Result = Join-Path $documents `
        'PowerShell\Microsoft.PowerShell_profile.ps1'
      $Ansible.Changed = $false
  register: shell_profile
  check_mode: false

- name: Shell | Ensure PowerShell directory exists
  ansible.windows.win_file:
    path: "{{ shell_profile.result | win_dirname }}"
    state: directory

- name: Shell | Configure oh-my-posh as the default PowerShell prompt
  community.windows.win_lineinfile:
    path: "{{ shell_profile.result }}"
    insertbefore: BOF
    create: true
    regex: "^oh-my-posh"
    line: "oh-my-posh init pwsh --config \"$env:POSH_THEMES_PATH\\{{ shell_oh_my_posh_theme }}.omp.json\" | Invoke-Expression"
