---
- name: SSH | Resolve configuration directory path
  ansible.windows.win_powershell:
    script: |
      $Ansible.Result = Join-Path $env:USERPROFILE '.ssh'
      $Ansible.Changed = $false
  register: ssh_directory
  check_mode: false

- name: SSH | Ensure configuration directory exists
  ansible.windows.win_file:
    path: "{{ ssh_directory.result }}"
    state: directory

- name: SSH | Deploy authorized keys
  ansible.windows.win_get_url:
    url: "{{ ssh_authorized_keys_url }}"
    dest: "{{ ssh_directory.result }}\\authorized_keys"
