---
- name: Cursor | Ensure destination directory exists
  ansible.windows.win_file:
    path: "{{ cursor_destination }}"
    state: directory

- name: Cursor | Install cursor files
  ansible.windows.win_copy:
    src: cursors/
    dest: "{{ cursor_destination }}\\"

- name: Cursor | Register selectable scheme
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Cursors\Schemes
    name: "{{ cursor_scheme_name }}"
    data: |-
      {%- for file in cursor_scheme_files -%}
      {{ cursor_destination }}\{{ file }}{{ "," if not loop.last else "" }}
      {%- endfor -%}
    type: string
