---
# Chezmoi
dotfiles_chezmoi_bin: /usr/bin/chezmoi
dotfiles_chezmoi_source_dir: "{{ dotfiles_repo_dir }}/chezmoi"

# Repository — shared with the Linux configuration
dotfiles_repo_dir: "{{ user_home }}/linux"
dotfiles_repo: "https://github.com/Zolkyed/linux.git"
dotfiles_repo_branch: "main"
