---
- name: VPN | Install packages
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: VPN
    install_chocolatey_packages: "{{ vpn_chocolatey_packages }}"
    install_scoop_packages: []
    install_winget_packages: []
