---
- name: Browser | Install packages
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: Browser
    install_chocolatey_packages: "{{ browser_chocolatey_packages }}"
    install_scoop_packages: []
    install_winget_packages: []

- name: Browser | Configure Brave DWORD policies
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\BraveSoftware\Brave
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    type: dword
    state: present
  loop: "{{ brave_policy_dword | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Browser | Configure Brave dictionary policies
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\BraveSoftware\Brave
    name: ExtensionSettings
    data: "{{ brave_extension_settings | to_json }}"
    type: string
    state: present
