---
profile: safety

warn_list:
  - yaml[line-length]
  - experimental

exclude_paths:
  - inventory/group_vars/*.sops.yml
  - inventory/host_vars/*.sops.yml

skip_list:
  - role-name
  - var-naming[no-role-prefix]
