TAB script-binding uosc/playlist

# Volume
WHEEL_UP      ignore
WHEEL_DOWN    ignore
UP            no-osd add volume  5
DOWN          no-osd add volume -5

# Seek
RIGHT no-osd seek  2 exact
LEFT  no-osd seek -2 exact
s script-binding skip-key
S script-binding skip-key
r no-osd seek -90
R no-osd seek -90
. frame-step
> frame-step
< frame-back-step
, frame-back-step

# Cycle
a cycle audio
A cycle audio
d cycle deband
D cycle deband
m no-osd cycle mute
M no-osd cycle mute
f cycle fullscreen
F cycle fullscreen
ESC set fullscreen no
MBTN_LEFT cycle pause
MBTN_LEFT_DBL cycle pause
SPACE cycle pause
c cycle sub
ctrl+c ignore

# Playlist
b script-binding uosc/prev
B script-binding uosc/prev
n script-binding uosc/next
N script-binding uosc/next

# Information
i script-binding stats/display-stats
I script-binding stats/display-stats-toggle
` script-binding console/enable

# AniList Updater
Ctrl+a       script-binding update_anilist       # Update AniList progress
Ctrl+b       script-binding launch_anilist       # Open the anime on AniList
Ctrl+d       script-binding open_folder          # Open the current anime folder
Ctrl+Shift+a script-binding correct_anime_id     # Correct anime, episode, or status

# Screenshot
x async screenshot
X async screenshot

# Speed
[ no-osd add speed -0.1
{ no-osd add speed -0.1
] no-osd add speed +0.1
} no-osd add speed +0.1
\ no-osd set speed 1
| no-osd set speed 1

# UOSC Menu Config

# File
# script-binding memo-history                                                               #! File > History
# script-binding uosc/playlist                                                              #! File > Playlist
# script-binding uosc/chapters                                                              #! File > Chapters
# script-binding uosc/open-file                                                             #! File > Open File
# script-binding uosc/show-in-directory                                                     #! File > Open in File Explorer

# Video
# cycle-values target-colorspace-hint yes no                 	                              #! Video > HDR

# Utilities
# script-binding uosc/keybinds                                                              #! Utilities > Keybinds
# script-binding uosc_screenshot/open-menu                                                  #! Utilities > Screenshot
# cycle-values loop-file "inf" "no" ; show-text "${?=loop-file==inf:File Looping: enabled}${?=loop-file==no:File Looping: disabled}" #! Utilities > Looping
# script-binding uosc/open-config-directory                                                 #! Utilities > Settings
# script-binding console/enable                                                             #! Utilities > Console
# script-binding uosc/update                                                                #! Utilities > Update uosc
# quit                                                                                      #! Quit
