ontop=no
border=no
keep-open=yes
save-position-on-quit=no
cache=yes
cursor-autohide=800
input-default-bindings=no
target-colorspace-hint=no

include="~~/configs/audio.conf"
include="~~/configs/deband.conf"
include="~~/configs/osd.conf"
include="~~/configs/quality.conf"
include="~~/configs/screenshot.conf"
include="~~/configs/sub.conf"
include="~~/configs/profile.conf"
