---
- name: Emulation | Install packages
  ansible.builtin.include_role:
    name: lib/packages
  vars:
    install_label: Emulation
    install_chocolatey_packages: "{{ emulation_chocolatey_packages }}"
    install_scoop_packages: []
    install_winget_packages: []
